#!/bin/bash

clear
cd ~

RED='\033[0;31m'
NC='\033[0m'
COLUMNS=12

print_header () {
echo -e "    ___                                      ${RED}__________${NC}";
echo -e "   /   |  ____  ____  ____  __  ______ ___  ${RED}/  _/_  __/${NC}";
echo -e "  / /| | / __ \/ __ \/ __ \/ / / / __ \`__ \ ${RED}/ /  / /${NC}   ";
echo -e " / ___ |/ / / / /_/ / / / / /_/ / / / / / /${RED}/ /  / /${NC}    ";
echo -e "/_/  |_/_/ /_/\____/_/ /_/\__, /_/ /_/ /_/${RED}___/ /_/${NC}     ";
echo "                         /____/                        ";
echo "";
}

print_menu () {
echo "1) Install Python"
echo "2) Install Reconnaissance tools"
echo "3) Install Initial access tools"
echo "4) Install Impact tools"
echo "5) Quit"
}


print_header
PS3='
Install tools: '
options=("Install Python" "Install Reconnaissance tools" "Install Initial access tools" "Install Impact tools" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Install Python")
	     apt-get update
	     apt-get install python3 python3-pip python3-dev -y
	    
	    #Return terminal to default
            clear
            print_header
            echo "Tools sucessfully installed. Install other tools or quit:
            "
            print_menu
	    ;;
	    
	"Install Reconnaissance tools")
            ;;
        "Install Initial access tools")
            #Install Blackeye
              git clone https://github.com/thewickedkarma/blackeye-im.git ~/AnonymIT/Reconnaissance/Blackeye
            cd ~/AnonymIT/Reconnaissance/Blackeye
             chmod +x ./setup.sh
              sh setup.sh
            
            #Install CardPwn
              git clone https://github.com/itsmehacker/CardPwn.git ~/AnonymIT/Reconnaissance/CardPwn
            cd ~/AnonymIT/Reconnaissance/CardPwn
              pip3 install -r requirements.txt
            
            #Install CrossLinked
              git clone https://github.com/m8sec/CrossLinked.git ~/AnonymIT/Reconnaissance/CrossLinked
            cd ~/AnonymIT/Reconnaissance/CrossLinked
              python3 setup.py install
            
            #Install Evilginx
              git clone https://github.com/kgretzky/evilginx2.git ~/AnonymIT/Reconnaissance/Evilginx
            
            #Install Fluxion
              git clone https://www.github.com/FluxionNetwork/fluxion.git ~/AnonymIT/Reconnaissance/Fluxion
            cd ~/AnonymIT/Reconnaissance/Fluxion
              sh ./fluxion.sh
            
            #Install Maigret
              pip install aiohttp==3.7.0
              git clone https://github.com/soxoj/maigret.git ~/AnonymIT/Reconnaissance/Maigret
            cd ~/AnonymIT/Reconnaissance/Maigret
              pip3 install -r requirements.txt
            
            #Install Sherlock
              git clone https://github.com/sherlock-project/sherlock.git ~/AnonymIT/Reconnaissance/Sherlock
            cd ~/AnonymIT/Reconnaissance/Sherlock
              python3 -m pip install -r requirements.txt
            
            #Install Social-Analyser
              git clone https://github.com/qeeqbox/social-analyzer.git ~/AnonymIT/Reconnaissance/Social-Analyser
            cd ~/AnonymIT/Reconnaissance/Social-Analyser
              pip3 install -r requirements.txt
            
            #Install SocialFish
              git clone https://github.com/UndeadSec/SocialFish.git ~/AnonymIT/Reconnaissance/SocialFish
            cd ~/AnonymIT/Reconnaissance/SocialFish
              python3 -m pip install -r requirements.txt
            
            #Install Trape
              git clone https://github.com/jofpin/trape.git ~/AnonymIT/Reconnaissance/Trape
            cd ~/AnonymIT/Reconnaissance/Trape
              pip3 install -r requirements.txt
            
            #Install Twitter profile Analyzer
              git clone https://github.com/x0rz/tweets_analyzer.git ~/AnonymIT/Reconnaissance/Twitter-Analyser
            cd ~/AnonymIT/Reconnaissance/Twitter-Analyser
              pip install -r requirements.txt
            
            #Install Twint
              git clone --depth=1 https://github.com/twintproject/twint.git ~/AnonymIT/Reconnaissance/Twint
            cd ~/AnonymIT/Reconnaissance/Twint
              pip3 install . -r requirements.txt
            
            #Install userrecon
              git clone https://github.com/lucmski/userrecon-py.git ~/AnonymIT/Reconnaissance/userrecon-py
            cd ~/AnonymIT/Reconnaissance/userrecon-py
             -H pip3 install -r requirements.txt
              python3 setup.py build
              python3 setup.py install
            
            #Return terminal to default
            clear
            print_header
            echo "Tools sucessfully installed. Install other tools or quit:
            "
            print_menu
            ;;
        "Install Impact tools")
            echo "you chose choice $REPLY which is $opt"
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
